import {db,owner,key,fail,fal,queueURL,runtime} from '@/lib/studio';
const active="('SUBMITTING','IN_QUEUE','IN_PROGRESS')";
export async function GET(){try{const u=await owner();const r=await db().prepare('SELECT id,name,kind,description,style,layout,status,images,selected,error,created FROM characters WHERE owner=? ORDER BY created DESC').bind(u).all();return Response.json(r.results,{headers:{'Cache-Control':'no-store'}});}catch(e){return fail(e);}}
export async function POST(req:Request){try{const u=await owner(req),b=await req.json() as any,d=db();
 if(b.action==='generate'){
  await key();if(typeof b.id!=='string'||!/^[0-9a-f-]{36}$/.test(b.id)||!['alien','human'].includes(b.kind)||!['portrait','sheet'].includes(b.layout)||!['spacecadet','natural','cinematic'].includes(b.style)||typeof b.description!=='string'||!b.description.trim()||b.description.length>4000)throw new Error('Describe your character and choose valid settings.');
  if(await d.prepare('SELECT id FROM characters WHERE id=? AND owner=?').bind(b.id,u).first())return Response.json({id:b.id});
  const pending=await d.prepare(`SELECT COUNT(*) as n FROM characters WHERE owner=? AND status IN ${active}`).bind(u).first<any>();if(pending.n>=4)throw new Error('Wait for your current characters to finish.');
  const style=b.style==='spacecadet'?'Spacecadet creative direction: strange but emotionally readable, distinctive organic anatomy, tactile practical creature effects, believable skin and asymmetry, everyday familiarity meets cosmic absurdity, restrained color, no generic science-fiction armor.':b.style==='natural'?'Candid natural-light photography, honest skin texture, believable everyday appearance.':'Cinematic character photography, sculpted soft light, subtle film texture.';
  const layout=b.layout==='sheet'?'A clean character reference sheet showing the SAME character in front full-body, side profile full-body, and three-quarter portrait views, with identical face, outfit and proportions in every view. Three clearly separated views on a neutral pale gray studio background. No lettering.':'One single full-body character portrait, entire body visible, clean neutral gray studio background, readable silhouette, detailed face.';
  const payload={prompt:`${layout}\nSubject: ${b.kind==='alien'?'An original extraterrestrial character':'A fictional human character'}. ${b.description}\n${style}\nNo watermark, no logos.`,image_size:b.layout==='sheet'?{width:1024,height:768}:{width:768,height:1024},num_images:2,num_inference_steps:4,enable_safety_checker:true,output_format:'jpeg'};
  const inserted=await d.prepare("INSERT OR IGNORE INTO characters (id,owner,name,kind,description,style,layout,status,input,created) VALUES (?,?,?,?,?,?,?,'SUBMITTING',?,?)").bind(b.id,u,String(b.name||'Untitled character').slice(0,100),b.kind,b.description,b.style,b.layout,JSON.stringify(payload),Date.now()).run();if(!inserted.meta.changes)return Response.json({id:b.id});
  try{const r=await fal('https://queue.fal.run/fal-ai/flux/schnell',{method:'POST',body:JSON.stringify(payload)});await d.prepare("UPDATE characters SET status='IN_QUEUE',status_url=?,response_url=? WHERE id=? AND owner=?").bind(queueURL(r.status_url),queueURL(r.response_url),b.id,u).run();}catch(e){await d.prepare("UPDATE characters SET status='CHECK_REQUIRED',error=? WHERE id=? AND owner=?").bind('Submission could not be confirmed. Check fal history before generating again.',b.id,u).run();throw e;}
  return Response.json({id:b.id});
 }
 const c=await d.prepare('SELECT * FROM characters WHERE id=? AND owner=?').bind(b.id,u).first<any>();if(!c)throw new Error('Character not found.');
 if(b.action==='rename'){const name=String(b.name||'').trim().slice(0,100);if(!name)throw new Error('Give your character a name.');await d.prepare('UPDATE characters SET name=? WHERE id=? AND owner=?').bind(name,b.id,u).run();return Response.json({ok:true});}
 if(b.action==='select'){if(!JSON.parse(c.images).includes(b.image))throw new Error('Choose one of this character’s generated images.');await d.prepare('UPDATE characters SET selected=? WHERE id=? AND owner=?').bind(b.image,b.id,u).run();return Response.json({ok:true});}
 if(b.action==='poll'){
  if(!['IN_QUEUE','IN_PROGRESS'].includes(c.status))return Response.json({ok:true});
  const s=await fal(c.status_url);if(s.status!=='COMPLETED'){if(['IN_QUEUE','IN_PROGRESS'].includes(s.status))await d.prepare('UPDATE characters SET status=? WHERE id=? AND owner=?').bind(s.status,c.id,u).run();return Response.json({ok:true});}
  try{if(s.error)throw new Error('The model could not complete this character.');const result=await fal(c.response_url);if(!result.images?.length)throw new Error('No character images returned.');const images:string[]=[];
   for(let i=0;i<Math.min(result.images.length,2);i++){if(result.has_nsfw_concepts?.[i])continue;const url=new URL(result.images[i].url);if(url.protocol!=='https:'||!(url.hostname==='fal.media'||url.hostname.endsWith('.fal.media')))throw new Error('Unexpected character image host.');const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(25000)});if(!r.ok)throw new Error('Could not save the character image.');const bytes=await r.arrayBuffer();if(bytes.byteLength>8*1024*1024)throw new Error('Character image is too large.');const asset=`char-${c.id}-${i}.jpg`;await runtime().BUCKET.put(asset,bytes,{httpMetadata:{contentType:'image/jpeg'}});await d.prepare('INSERT OR IGNORE INTO assets (id,owner,mime,name) VALUES (?,?,?,?)').bind(asset,u,'image/jpeg',c.name+'.jpg').run();images.push(asset);}
   if(!images.length)throw new Error('The model blocked these images. Try a different description.');await d.prepare("UPDATE characters SET status='COMPLETED',images=?,error=NULL WHERE id=? AND owner=?").bind(JSON.stringify(images),c.id,u).run();
  }catch(e){await d.prepare("UPDATE characters SET status='FAILED',error=? WHERE id=? AND owner=?").bind((e as Error).message.slice(0,500),c.id,u).run();}return Response.json({ok:true});
 }
 throw new Error('Unknown character action.');
 }catch(e){return fail(e);}}
