import { env } from 'cloudflare:workers';
import { headers } from 'next/headers';
export const runtime = () => env as unknown as { DB: D1Database; BUCKET: R2Bucket; FAL_KEY?: string; KEY_ENCRYPTION_SECRET?: string };
export function db(){const d=runtime().DB;if(!d)throw new Error('Workspace storage is unavailable. Please try again.');return d;}
export async function owner(req?:Request){const h=await headers();const id=h.get('oai-authenticated-user-id');if(!id)throw new Error('Please sign in to open your workspace.');if(req&&req.method!=='GET'){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new Error('Request origin is not allowed.');}return id;}
export function fail(e:unknown){return Response.json({error:e instanceof Error?e.message:'Something went wrong. Please try again.'},{status:400,headers:{'Cache-Control':'no-store'}});}
async function encryptionKey(){const secret=runtime().KEY_ENCRYPTION_SECRET;if(!secret)throw new Error('Secure connection storage is not ready.');const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret));return crypto.subtle.importKey('raw',hash,'AES-GCM',false,['encrypt','decrypt']);}
export async function saveKey(user:string,value:string){if(!value.trim()||value.length>500||/[\r\n]/.test(value))throw new Error('Enter a valid fal API key.');const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(user)},await encryptionKey(),new TextEncoder().encode(value.trim()));const packed=JSON.stringify({iv:Array.from(iv),data:Array.from(new Uint8Array(encrypted))});await db().prepare('INSERT INTO connections (owner,encrypted) VALUES (?,?) ON CONFLICT(owner) DO UPDATE SET encrypted=excluded.encrypted').bind(user,packed).run();}
export async function connected(user:string){return !!runtime().FAL_KEY||!!await db().prepare('SELECT owner FROM connections WHERE owner=?').bind(user).first();}
export async function key(){if(runtime().FAL_KEY)return runtime().FAL_KEY!;const user=await owner();const row=await db().prepare('SELECT encrypted FROM connections WHERE owner=?').bind(user).first<{encrypted:string}>();if(!row)throw new Error('Connect your fal API key to start generating. Your drafts are saved.');const packed=JSON.parse(row.encrypted);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(packed.iv),additionalData:new TextEncoder().encode(user)},await encryptionKey(),new Uint8Array(packed.data));return new TextDecoder().decode(plain);}
export function queueURL(s:string){const u=new URL(s);if(u.origin!=='https://queue.fal.run')throw new Error('Unexpected generation service URL.');return u.href;}
export async function fal(url:string,init:RequestInit={}){const r=await fetch(queueURL(url),{...init,redirect:'error',headers:{'Content-Type':'application/json',Authorization:`Key ${await key()}`,...init.headers},signal:AbortSignal.timeout(25000)});const data=await r.json() as any;if(!r.ok)throw new Error(r.status===401?'fal rejected the API key. Check your connection.':r.status===402?'Your fal account needs credits.':r.status===429?'fal is busy. Please wait before trying again.':`fal request failed (${r.status}). Check your fal dashboard for details.`);return data;}
export const defaults={prompt:'',duration:5,resolution:'768P',aspect_ratio:'16:9',prompt_expansion_mode:'balanced',seed:'',image:'',endImage:''};
export function parseDraft(v:any){if(!v||typeof v.prompt!=='string'||v.prompt.length>10000)throw new Error('Enter a prompt of up to 10,000 characters.');if(![5,10,15].includes(v.duration)||!['480P','768P'].includes(v.resolution)||!['21:9','16:9','4:3','1:1','3:4','9:16'].includes(v.aspect_ratio)||!['balanced','quality'].includes(v.prompt_expansion_mode))throw new Error('Choose valid generation settings.');if(v.seed!==''&&(!Number.isInteger(Number(v.seed))||Number(v.seed)<0||Number(v.seed)>2147483647))throw new Error('Seed must be between 0 and 2147483647.');return {prompt:v.prompt,duration:v.duration,resolution:v.resolution,aspect_ratio:v.aspect_ratio,prompt_expansion_mode:v.prompt_expansion_mode,seed:String(v.seed??''),image:String(v.image||''),endImage:String(v.endImage||'')};}
export async function imageData(id:string,user:string){if(!id)return undefined;const a=await db().prepare('SELECT * FROM assets WHERE id=? AND owner=?').bind(id,user).first<any>();if(!a)throw new Error('Reference image was not found.');const object=await runtime().BUCKET.get(id);if(!object)throw new Error('Reference image is unavailable.');const bytes=new Uint8Array(await object.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return `data:${a.mime};base64,${btoa(binary)}`;}
